version: '3'
services:
  # Base configurations
  mqtt-broker:
    image: eclipse-mosquitto:1.5.9
    container_name: unify-mqtt-broker
    volumes:
      - ./mosquitto-config:/mosquitto/config/
    ports:
      - '1883:1883'
    command: mosquitto
    networks:
      - mqtt-network
    restart: unless-stopped

  unify-base:
    image: unify-runtime:latest
    build:
      context: .
      args:
        - DEBIAN_PACKAGES
    entrypoint: /bin/true

  # Developer applications
  unify-dev-gui-server:
    image: unify-runtime
    container_name: unify-dev-gui-server
    restart: on-failure
    depends_on:
      - unify-base
      - mqtt-broker
      - unify-dev-gui-api
    networks:
      - mqtt-network
    entrypoint: dev-gui-client --REACT_APP_MQTT_HOST mqtt-broker
    ports:
      - "3080:3080"

  unify-dev-gui-api:
    image: unify-runtime
    container_name: unify-dev-gui-api
    restart: on-failure
    depends_on:
      - unify-base
      - mqtt-broker
    networks:
      - mqtt-network
    entrypoint: dev-gui-api
    ports:
      - "1337:1337"

  # Application services
  unify-gms:
    image: unify-runtime
    container_name: unify-gms
    restart: on-failure
    depends_on:
      - unify-base
      - mqtt-broker
    networks:
      - mqtt-network
    entrypoint: uic-gms --mqtt.host mqtt-broker --mqtt.client_id gms-portable_runtime
    volumes:
      - unify_gms:/var/lib

  unify-upvl:
    image: unify-runtime
    container_name: unify-upvl
    restart: on-failure
    depends_on:
      - unify-base
      - mqtt-broker
    networks:
      - mqtt-network
    entrypoint: uic-upvl --mqtt.host mqtt-broker --mqtt.client_id upvl-portable_runtime
    volumes:
      - unify_upvl:/var/lib

  unify-nal:
    image: unify-runtime
    container_name: unify-nal
    restart: on-failure
    depends_on:
      - unify-base
      - mqtt-broker
    networks:
      - mqtt-network
    entrypoint: uic-nal --mqtt.host mqtt-broker --mqtt.client_id nal-portable_runtime
    volumes:
      - unify_nal:/var/lib

  unify-image-provider:
    image: unify-runtime
    container_name: unify-image-provider
    restart: on-failure
    depends_on:
      - unify-base
      - mqtt-broker
    networks:
      - mqtt-network
    entrypoint: uic-image-provider --mqtt.host mqtt-broker --mqtt.client_id image-provider-portable_runtime
    volumes:
      - unify_image_provider:/var/lib

  unify-upti-cap:
    image: unify-runtime
    container_name: unify-upti-cap
    restart: on-failure
    depends_on:
      - unify-base
      - mqtt-broker
    networks:
      - mqtt-network
    entrypoint: uic-upti-cap --mqtt.host mqtt-broker --mqtt.client_id upti-cap-portable_runtime
    volumes:
      - unify_upti_cap:/var/lib

  unify-positioning:
    image: unify-runtime
    container_name: unify-positioning
    restart: on-failure
    depends_on:
      - unify-base
      - mqtt-broker
    networks:
      - mqtt-network
    entrypoint: positioning --mqtt.host mqtt-broker --mqtt.client_id positioning-portable_runtime
    volumes:
      - unify_positioning:/var/lib

  # Protocol controllers
  unify-zpc:
    image: unify-runtime
    container_name: unify-zpc
    restart: on-failure
    depends_on:
      - unify-base
      - mqtt-broker
    networks:
      - mqtt-network
    environment:
      - ZPC_DEVICE_TTY
      - ZPC_DEVICE_IP
      - ZPC_CONFIG_ARGS
    devices:
      - "${ZPC_DEVICE_TTY:-/dev/null}:${ZPC_DEVICE_TTY:-/dev/null}"
    entrypoint: "/unify/run_zpc.sh --mqtt.host mqtt-broker ${ZPC_CONFIG_ARGS} --mqtt.client_id zpc-portable_runtime"
    volumes:
      - unify_zpc:/var/lib

  unify-zigpc:
    image: unify-runtime
    container_name: unify-zigpc
    restart: on-failure
    depends_on:
      - unify-base
      - mqtt-broker
    networks:
      - mqtt-network
    environment:
      - ZIGPC_DEVICE_TTY
      - ZIGPC_DEVICE_IP
      - ZIGPC_PORT
    devices:
      - "${ZIGPC_DEVICE_TTY:-/dev/null}:${ZIGPC_DEVICE_TTY:-/dev/null}"
    entrypoint: "/unify/run_zigpc.sh --mqtt.host mqtt-broker --zigpc.tc_use_well_known_key 0 --mqtt.client_id zigpc-portable_runtime"
    volumes:
      - unify_zigpc:/var/lib

  unify-aoxpc:
    image: unify-runtime
    container_name: unify-aoxpc
    restart: on-failure
    depends_on:
      - unify-base
      - mqtt-broker
      - unify-positioning
    networks:
      - mqtt-network
    environment:
      - AOXPC_DEVICE_TTY
      - AOXPC_DEVICE_IP
      - AOXPC_PORT
    devices:
      - "${AOXPC_DEVICE_TTY:-/dev/null}:${AOXPC_DEVICE_TTY:-/dev/null}"
    entrypoint: "/unify/run_aoxpc.sh --mqtt.host mqtt-broker --mqtt.client_id aoxpc-portable_runtime"
    volumes:
      - unify_aoxpc:/var/lib

  unify-multiprotocol:
    image: unify-runtime
    container_name: unify-multiprotocol
    restart: on-failure
    depends_on:
      - unify-base
      - mqtt-broker
    networks:
      - mqtt-network
    environment:
      - MULTIPROTOCOL_DEVICE_TTY
      - MULTIPROTOCOL_DEVICE_IP
      - MULTIPROTOCOL_PORT
      - MULTIPROTOCOL_SELECTIONS=Zigbee
    devices:
      - "${MULTIPROTOCOL_DEVICE_TTY:-/dev/null}:${MULTIPROTOCOL_DEVICE_TTY:-/dev/null}"
    entrypoint: "/unify/run_multiprotocol.sh --mqtt.host mqtt-broker --mqtt.client_id multiprotocol-portable_runtime"
    volumes:
      - unify_multiprotocol:/var/lib

  unify-matter-bridge:
    image: unify-runtime
    container_name: unify-matter-bridge
    restart: on-failure
    depends_on:
      - unify-base
      - mqtt-broker
    networks:
      - mqtt-network
    entrypoint: "/unify/run_matter_bridge.sh --mqtt.host mqtt-broker --mqtt.client_id matter-bridge"
    volumes:
      - unify_matter_bridge:/var/lib

  unify-emd:
    image: unify-runtime
    container_name: unify-emd
    restart: on-failure
    depends_on:
      - unify-base
      - mqtt-broker
    networks:
      - mqtt-network
    environment:
      - EMD_CLUSTER_ARG
      - EMD_DEVICE_TYPE_ARG
    entrypoint: "/unify/run_emd.sh --mqtt.host mqtt-broker --mqtt.client_id emd-portable_runtime ${EMD_CLUSTER_ARG} ${EMD_DEVICE_TYPE_ARG}"
    volumes:
      - unify_emd:/var/lib

volumes:
  unify_gms:
  unify_upvl:
  unify_nal:
  unify_image_provider:
  unify_upti_cap:
  unify_positioning:
  unify_zpc:
  unify_zigpc:
  unify_aoxpc:
  unify_multiprotocol:
  unify_matter_bridge:
  unify_emd:

networks:
  mqtt-network:
    driver: bridge
